root: true
extends: actano-base

plugins:
  - 'mocha-no-only'
  - 'import'

overrides:
  - files:
      - 'test/**/*.js'
      - 'test/**/*.jsx'
      - 'test/**/*.ts'
      - 'test/**/*.tsx'
    env:
      mocha: true
    rules:
      mocha-no-only/mocha-no-only: 'error'
    settings:
      import/core-modules:
        - chai
        - sinon