language: node_js
node_js:
- '8'
- '10'
cache: yarn
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
script: npm run ci
deploy:
  provider: npm
  skip_cleanup: true
  email: marcus.mennemeier@actano.de
  on:
    tags: true
    repo: actano/rplan-logger
    node: '8'
  api_key:
    secure: Q6A3zIMGK4ytnDL24IVjZd06a4DsV5k0EfotNhf9DKd0AaChH3Q/XzPmsnISv0N7jJoykw7Oqa8rl81OgGSiW8nfmgLajDQvwIMdzObfDKu+euoKADvKtaAtHvBg+5sX1sI6OSm3mJ5GMsuENSXJe2fZqv1lZvtv26iScIpb3yBfOm4vK935IzrJwrKEI89MJhuAk7oB8HteImMOXHDdLYRmLPBKbNdos/xZSryQ7lRTwr3JqqxcypA65tMo6KHL+KL/eMuuKDKDiIizCa6No98BCKvlkooFxjtx52tYPXExALJAn0vpFbg7IJXHKyQFanxrn2mC4C0q1UeS5Vhy9B8KtmLmw//cqAsHWJs3h0+cr+7COkgjcAMjVXOBiRWWXEJ6F6f4Mi9qEvOUL6EH5O5UNmdQrofTqbaAFBLyyBEZ5qPildo5vHZEUIW+lTbcU5bTQbgMNyXZiNx7IgXN+cMb30G/YQEM0aygwqzN+47kuJEdRazfBJb3CNsHoLn1eRRoZMdo2HjOtCs/iQKP74WQ0fYb69H9YyG/xfs2He4CvWgnCbQO5AaL+I4Ow8o6fq0MCzjW1KTetIfpLlzCwOOi5vuwj5A1Q6PSfaNjCBZEKKYDPfioFGG09mHs4DmZyosvkdAujUGUX/LBe+E4oqPbp9CRzYsSrjM/Go2y0bY=
after_script: greenkeeper-lockfile-upload
env:
  global:
    secure: A/mk7+nzETU9ByCAyWhIDBvlGe9MkoIszTGasg/inrbH82Q6t9dNq5aYmZKgYRmHM4P5AcaDypaMf0pVsvhxarURy5fKSf44W4zaggPWkKegwv0oZaFlQaa29pzDTe/r1bg9Yx4tkX1bXy+1HM+mOuWm6xteCW0UNV1HA517g6GGiz2lU7QSg9Xu9B6vcX+X+uMhf5QNExTIv7ZOrOI27gjX9cRZjGEXSaVhaq/05sfdYGACWQKgLAkPOKBj0oVlkLXPcl4/7/Dzp4fEXy+8XyJ247lvVIS6Z9u2YcuJNcZ4hY9qAkoiZ9lkTdPogaG7fviVK2U3ezcNEBRDs4cqPTjgJzyRu3hh12vAB3S8yYeK2Mx9wgAd9ieom72klKqkqH3W44tSoeT4gx9JvykJhCpH2NAX9wD6xlOgnsrK5UJpwUlIickgXnoF2vlSwT1uYXwq2OQw+0JQ4voQuh0/BWXUOmZS8N5SvQ7E8EmD7EgjIxuHWyB5hl/u8jSamYdAnwudxf3GxTmAuDs6g7zw6FzN3B77XvuGH74OTYgVgXRoJH/gGd0xO6lBoCCe9XQzCGLS8onwOcbQn7qKGYo5c7cr2dbs6tiHiKE8el5M5R8ma5/zJnFt65juhuM9Hs7Q61ynvWvQvUaELIvfm9nIid79UOPe1G3mcO02yw+vdZ0=
